// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYoYF4gKSUpF4Woih4BzOVvSBAVi3Dkk4',
    appId: '1:629906811435:web:2239a2926469215aa2d86e',
    messagingSenderId: '629906811435',
    projectId: 'task-682ca',
    authDomain: 'task-682ca.firebaseapp.com',
    storageBucket: 'task-682ca.firebasestorage.app',
    measurementId: 'G-QV38FY44RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfSnqpLOQkHUthPjJkkvI3OhW-lpXtJlE',
    appId: '1:629906811435:android:0020cc595c354e8ea2d86e',
    messagingSenderId: '629906811435',
    projectId: 'task-682ca',
    storageBucket: 'task-682ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-V4OSKT0-qsVkudx7gUyur0lbJhkTN0A',
    appId: '1:629906811435:ios:58dcb86553901e8ba2d86e',
    messagingSenderId: '629906811435',
    projectId: 'task-682ca',
    storageBucket: 'task-682ca.firebasestorage.app',
    iosBundleId: 'com.example.resTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-V4OSKT0-qsVkudx7gUyur0lbJhkTN0A',
    appId: '1:629906811435:ios:58dcb86553901e8ba2d86e',
    messagingSenderId: '629906811435',
    projectId: 'task-682ca',
    storageBucket: 'task-682ca.firebasestorage.app',
    iosBundleId: 'com.example.resTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYoYF4gKSUpF4Woih4BzOVvSBAVi3Dkk4',
    appId: '1:629906811435:web:1c14050ed7000662a2d86e',
    messagingSenderId: '629906811435',
    projectId: 'task-682ca',
    authDomain: 'task-682ca.firebaseapp.com',
    storageBucket: 'task-682ca.firebasestorage.app',
    measurementId: 'G-L04787164D',
  );
}
